language: python
env:
  DEV_DATABASE_URL="dbname='fastdev_db' user='postgres' host='127.0.0.1' port='5432' password=''"
  TEST_DATABASE_URL="dbname='fasttest_db' user='postgres' host='127.0.0.1' port='5432' password=''"
  ENV_CONFIG="test_env"

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install
  - pipenv install coveralls codecov

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE fasttest_db' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

  - psql -c 'CREATE DATABASE fastdev_db' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres


script:
  - pytest --cov=app/tests --cov-report=html

after_success:
  - coveralls
  - codecov --token=31be0875-48ba-4884-9a8a-616f51b6cb6f